### ISSUE TITLE
It is working up to 20 or 30 records, that's it. 

### ISSUE THREAD

**Issue by cyborg2006** [aarnhub/instagram-scraper-python#1]
Code is working 1-2 minutes max automatically.  I found one solution, but time consuming. 
When I scroll the pop-up by hand frequently while code is working background, it is working and recording all the data I need. Automatic scrolling is not working properly even I tried to many time delay options. Below is the brief error message I received during 25th record. 

check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[4]/div/div/div[2]/ul/div/li[25]"}

**Comment by aarnhub** [comment]
fixed
